class AppText{

  

  static const appTextList = [
    "Choose Location",
    "Choose your location for near hospitals",
    "Country",
    "Address",
    "Next",
    "Choose Language",
    "Contact Us",
    "FAQ",
    "Terms",
    "Pending",
    "No Patients found",
    "Appointments Call",
    "Medication List",
    "No Prescription found",
    "No Medication Suggest",
    "Upcoming",
    "Completed",
    "You can now make multiple doctoral appointments at once. You can appointments at once. You can..."
        "canceled",
    "Find here!",
    "My Appointments",
    "My Appointment",
    "Changes to the Service and/or Terms refer to our commitment to continuously improve and update our platform to enhance user experience and comply with legal requirements. We reserve the right to modify or discontinue any aspect of the service, including features and functionalities, at any time without prior notice. Additionally, we may revise these terms to reflect changes in our business practices, industry standards, or regulatory obligations. Updates to the terms will be effective immediately upon posting on our website or app. Continued use of the service constitutes acceptance of the revised terms."
        "Help and Support",
    "Terms & Conditions",
    "Choose language for app to show",
    "French",
    "Prescription",
    "Primary Language",
    // "Our Legal and Policies outline the terms and conditions governing the use of our services. By accessing or using our platform, you agree to abide by these terms, which include but are not limited to, user responsibilities, intellectual property rights, privacy practices, and dispute resolution procedures. We reserve the right to update or modify these terms at any time, and your continued use of the platform constitutes acceptance of any changes. Please review our Legal and Policies regularly for updates."
    "Arabic",
    "English",
    "Spanish",
    "Expert Doctor",
    "Advice Online",
    "Access top-tier medical expertise from the comfort of your home. Our platform connects you with specialized doctors for personalized advice and care, anytime, anywhere.",
    "Doctor Support, Always",
    "Ready",
    "Our dedicated doctors are here to support you 24/7. Whether it's a simple consultation or urgent advice, you can count on us to be there when you need it most.",
    "Stay Healthy,",
    "Stay Connected",
    "Your health is our priority. Stay connected with your healthcare providers and maintain your well-being through seamless, continuous care and support.",
    "Choose Account Type",
    "Patient",
    "Health Professional",
    "Login",
    "Changes to the Service and/or Terms:",
    "Register",
    "Sign In",
    "Access your account securely. Sign in to manage your personalized experience.",
    "Email",
    // "Changes to the Service and/or Terms refers to our commitment to continuously improve and update our platform to enhance user experience and comply with legal requirements. We reserve the right to modify or discontinue any aspect of the service, including features, functionalities, and access levels, at any time without prior notice. Additionally, we may revise these terms of service to reflect changes in our business practices, industry standards, or regulatory obligations. Any updates to the terms will be effective immediately upon posting on our website or app, and your continued use of the service constitutes acceptance of the revised terms. We encourage users to review the terms regularly to stay informed about any changes. If you do not agree with the updated terms, you may discontinue using the service. However, continued use of the service following updates indicates your acceptance of the modifications."
    "Password",
    "Profile",
    "Enter email",
    "Forgot Password?",
    "Forgot Password",
    "Or Continue With",
    "Don’t have an account?",
    "Sign Up",
    " Sign Up ",
    "here",
    "Create an Account",
    "Sign up today for personalized health insights and exclusive member perks!",
    "Confirm Password",
    "Remember Password",
    "Already have an account?",
    "Reset your password securely for uninterrupted access to your account.",
    "Send OTP",
    "Verify OTP",
    "Verify",
    "Enter OTP code received to authenticate your identity and complete verification",
    "Did’nt receive email?",
    "Resend",
    "Personalized Dashboard",
    "Appointment Management (Limited to 15 Appointment/Month",
    "Access to Medical Resources (Limited Selection)",
    "Basic Notifications & Alerts",
    "Multilingual Support",
    "Free",
    "Basic",
    "Select",
    "Premium",
    "Advance",
    "Get Started",
    "350 dhs/Month",
    "All Features from Free Offer",
    "Smart Agenda",
    "Appointment Confirmation and Reminders",
    "Practice/Clinic Appointment Management",
    "Video Consultation / Home Visits / In-office / At Clinic",
    "Instant Messaging",
    "Access for Assistants",
    "SMS Reminders",
    "Prescription Creation",
    "DocShare",
    "550 dhs/Month",
    "All Features from Basic Offer",
    "Comprehensive Access to Electronic Medical Records (EMR)",
    "Unlimited Electronic Prescriptions",
    "Advanced Patient Management",
    "Detailed Reports & Analytics",
    "Unlimited Document Management",
    "Integration with Medical Devices",
    "Advance Notifications and Alerts",
    "Offline Access",
    "Priority Customer Support",
    "Automated Search",
    "Let’s Find Your Doctor",
    "Upcoming Schedule",
    "Doctor Speciality",
    "Top Doctor",
    "Dr.",
    "Personal Info",
    "Payment",
    "Language",
    "Help Center",
    "Log Out",
    "Are you sure you want to log out",
    "Logout",
    "Cancel",
    "View All",
    "Appointment",
    "Notification",
    "Latest Update",
    "My Favourite Doctor",
    "Make an appointment",
    "No Found",
    "About Doctor",
    "Fees Information",
    "Schedules",
    "Patients details",
    "Full Name",
    "Tell doctor about your problem....",
    "Max 250 words",
    "Name",
    "Gallery",
    "Camera",
    "Payment Methods",
    "Appointment Date",
    "Add Card",
    "Confirm Appointment",
    "Bank Account",
    "Credit / Debit Card",
    "Pay Through Payment Code",
    "Manage Notification",
    "Save Changes",
    "Date of Birth",
    "Edit Profile",
    "Hi",
    "Female",
    "Legal and Policies",
    "File should be pdf, docx or pptx",
    "Add a file",
    "or drop it here",
    "Continue",
    "Select Your Age Range",
    "File should be pdf, docs or ppt",
    "Please enter a valid phone number with country code",
    "Tell doctor about your problem...",
    "Gender or Age is Missing!",
    "Paypal",
    "Bank Transfer",
    "Mastercard",
    "Phone Number",
    "Gender",
    "Male",
    "Patients",
    "Reviews",
    "Online",
    "Time:",
    "Date:",
    "Total",
    "Years experience",
    "Select Appointment Time!",
    "Write Your Problem",
    "Any Documented Test Reports",
    "You can now make multiple doctoral appointments at once",
    "You can now make multiple doctoral appointments at once You can  appointments at once You can",
    "Make Payment",
    "Consulting",
    "Other Manipulation",
    "Other Service",
    "Total",
    "Booking Confirmed",
    "is a highly skilled cardiologist dedicated to providing exceptional cardiac care. With",
    "Start Appointment",
    "Video Call Ended",
    "Recording have been saved in history",
    "Would you recommend Dr. Marvin to your friends?",


    //Start from here
    "Privacy",
    "Payment management",
    "Software Management",
    "Your Balance",
    "Withdraw",
    "This week’s income",
    "Quick Access",
    "Appointment\nReminders",
    "Appointments",
    "Patient Details",
    "Total Patient",
    "Prescription sent",
    "Documents shared",
    "Appointment Reminders",
    "Appointment",
    "All",
    "Patient Management",
    "Message",
    "Age",
    "Personal Details",
    "Check\nReport",
    "EMR",
    "Results",
    "E-prescription",
    "Active Medical Conditions",
    "Chat",
    "Lab Report",
    "Send Report",
    "Recent Tests",
    "Result",
    "PDF File",
    "Send Document to",
    "Write Prescription",
    "Appointment Reminder",
  ];

}